# Generated by Django 4.2.2 on 2023-07-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("io_module", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iomodule",
            old_name="type",
            new_name="module_type",
        ),
    ]
