# Generated by Django 4.2.2 on 2023-07-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_module', '0003_alter_iomodule_module_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iomodule',
            name='module_type',
            field=models.CharField(default='io', editable=False, max_length=10),
        ),
    ]
