# Generated by Django 4.2.2 on 2023-07-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_module", "0006_rename_iomodule_iomodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iomodel",
            name="raidlevel",
            field=models.CharField(
                choices=[
                    ("r0", "R0"),
                    ("r1", "R1"),
                    ("r5", "R5"),
                    ("r6", "R6"),
                    ("r10", "R10"),
                    ("r50", "R50"),
                    ("r60", "R60"),
                    ("jbod", "JBOD"),
                ],
                default="R0",
                max_length=12,
            ),
        ),
    ]
