# Generated by Django 4.2.2 on 2023-07-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_module", "0007_alter_iomodel_raidlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="iomodel",
            name="_use_count",
            field=models.IntegerField(default=0),
        ),
    ]
