# Generated by Django 4.2.2 on 2023-07-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_module', '0008_iomodel__use_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iomodel',
            name='_use_count',
            field=models.IntegerField(default=1),
        ),
    ]
