# Generated by Django 4.2.2 on 2023-07-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_alter_configmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configmodel",
            name="_use_count",
            field=models.IntegerField(default=0),
        ),
    ]
