# Generated by Django 4.2.2 on 2023-07-19 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0004_alter_configmodel__use_count_alter_configmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='_use_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='module_type',
            field=models.CharField(default='config', max_length=10),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
