# Generated by Django 4.2.2 on 2023-07-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_configmodel__use_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='module_type',
            field=models.CharField(default='config', editable=False, max_length=10),
        ),
    ]
