# Generated by Django 4.2.2 on 2023-07-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_alter_configmodel_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configmodel",
            name="size",
        ),
    ]
