# Generated by Django 4.2.2 on 2023-07-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0006_remove_configmodel_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="configmodel",
            name="size",
            field=models.IntegerField(default=10),
        ),
    ]
