# Generated by Django 4.2.2 on 2023-07-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0007_configmodel_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configmodel",
            name="raid",
            field=models.CharField(
                choices=[
                    ("1", "R0"),
                    ("2", "R1"),
                    ("3", "R5"),
                    ("4", "R6"),
                    ("5", "R10"),
                    ("6", "R50"),
                    ("7", "R60"),
                    ("8", "JBOD"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
