# Generated by Django 4.2.2 on 2023-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0008_alter_configmodel_raid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configmodel",
            name="raid",
            field=models.CharField(
                choices=[
                    ("R0", "R0"),
                    ("R1", "R1"),
                    ("R5", "R5"),
                    ("R6", "R6"),
                    ("R10", "R10"),
                    ("R50", "R50"),
                    ("R60", "R60"),
                    ("JBODs", "JBODs"),
                ],
                max_length=20,
            ),
        ),
    ]
