# Generated by Django 4.2.2 on 2023-07-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0009_alter_configmodel_raid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configmodel",
            name="raid",
        ),
    ]
