# Generated by Django 4.2.2 on 2023-07-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0010_remove_configmodel_raid"),
    ]

    operations = [
        migrations.AddField(
            model_name="configmodel",
            name="raid",
            field=models.CharField(
                choices=[
                    ("r0", "R0"),
                    ("r1", "R1"),
                    ("r5", "R5"),
                    ("r6", "R6"),
                    ("r10", "R10"),
                    ("r50", "R50"),
                    ("r60", "R60"),
                    ("jbod", "JBOD"),
                ],
                default="r0",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
