# Generated by Django 4.2.2 on 2023-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0011_configmodel_raid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configmodel",
            name="module_type",
            field=models.CharField(default="config", editable=False, max_length=10),
        ),
    ]
