# Generated by Django 4.2.2 on 2023-07-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0013_alter_configmodel_dtabcount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configmodel",
            name="_use_count",
            field=models.IntegerField(default=0),
        ),
    ]
