# Generated by Django 4.2.2 on 2023-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cqid", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("summary", models.TextField(max_length=2000)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.JSONField(null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "test_cases",
                    models.ManyToManyField(
                        related_name="test_case", to="testcase.testcase"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="testcase",
            name="test_steps_list",
            field=models.ManyToManyField(to="testcase.teststep"),
        ),
    ]
