# Generated by Django 4.2.2 on 2023-08-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teststep",
            name="test_cases",
            field=models.ManyToManyField(
                related_name="teststep", to="testcase.testcase"
            ),
        ),
    ]
