# Generated by Django 4.2.2 on 2023-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0004_testcase_created_on_testcase_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststep',
            name='test_cases',
            field=models.ManyToManyField(related_name='test_case', to='testcase.testcase'),
        ),
    ]
