# Generated by Django 4.2.2 on 2023-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0006_alter_teststep_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teststep",
            name="step",
            field=models.CharField(max_length=3000),
        ),
    ]
