# Generated by Django 4.2.2 on 2023-07-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0008_alter_teststep_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_steps_list',
            field=models.ManyToManyField(related_name='test_step', to='testcase.teststep'),
        ),
    ]
