# Generated by Django 4.2.2 on 2023-07-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0010_alter_testcase_test_steps_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_steps_list',
            field=models.ManyToManyField(to='testcase.teststep'),
        ),
    ]
