# Generated by Django 4.2.2 on 2023-06-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configmodel",
            name="raid",
            field=models.CharField(
                choices=[
                    ("R0", "R0"),
                    ("R1", "R1"),
                    ("R5", "R5"),
                    ("R6", "R6"),
                    ("JBODs", "JBODs"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="configmodel",
            name="size",
            field=models.CharField(max_length=10),
        ),
    ]
