# Generated by Django 4.2.2 on 2023-07-05 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_configmodel_num_pds_configmodel_dtabcount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configmodel",
            name="num_vds",
        ),
    ]
