# Generated by Django 4.2.2 on 2023-07-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_configmodel_num_vds'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmodel',
            name='type',
            field=models.CharField(default='config', editable=False, max_length=15),
        ),
    ]
