# Generated by Django 4.2.2 on 2023-07-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_configmodel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configmodel",
            name="init",
            field=models.CharField(
                choices=[
                    ("full", "FULL"),
                    ("fast", "FAST"),
                    ("no init", "No INIT"),
                    ("autobgi", "AutoBGI"),
                ],
                max_length=10,
            ),
        ),
    ]
