# Generated by Django 4.2.2 on 2023-07-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_configmodel_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='readpolicy',
            field=models.CharField(choices=[('ra', 'RA'), ('nora', 'NORA')], max_length=6),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='writepolicy',
            field=models.CharField(choices=[('wb', 'WB'), ('wt', 'WT')], max_length=6),
        ),
    ]
