# Generated by Django 4.2.2 on 2023-07-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_configmodel_readpolicy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configmodel",
            old_name="type",
            new_name="module_type",
        ),
    ]
