# Generated by Django 4.2.2 on 2023-07-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_type_configmodel_module_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='module_type',
            field=models.CharField(default='config', max_length=15),
        ),
    ]
