# Generated by Django 4.2.2 on 2023-07-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_configmodel_module_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='module_type',
            field=models.CharField(default='config', editable=False, max_length=15),
        ),
    ]
